"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";

type S={id:string;name:string;className:string};
type Task={id:string;subject:string;lesson:string;skill?:string;taskText:string;status:"PENDING"|"COMPLETED";source:"AUTO"|"MANUAL"};
type WeekItem={id:string;subject:string;lesson:string;expectedTask?:string;contentStatus:"READY"|"INCOMPLETE"};
type B={
 student:S;
 previewStudents?:S[];
 mode:"STUDENT"|"TEACHER_PREVIEW";
 subjects:{id:string;name:string;order:number}[];
 valueStars:{id:string}[];
 today:{date:string;day:string;tasks:Task[];incompleteSubjects:string[]};
 week:null|{week:number;weekStart:string;days:{day:string;date:string;subjects:WeekItem[]}[]};
};

export default function StudentPage(){
 const [bundle,setBundle]=useState<B|null>(null);const [id,setId]=useState("");const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [error,setError]=useState("");
 const load=useCallback(async(selectedId="")=>{setLoading(true);try{const query=selectedId?`?studentId=${encodeURIComponent(selectedId)}`:"";const response=await fetch(`/api/student/learning${query}`,{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error(payload.error||"تعذر تحميل مهام الطالب");setBundle(payload);setError("");if(payload.mode==="TEACHER_PREVIEW"&&!selectedId&&payload.student?.id)setId(payload.student.id);}catch(cause){setError(cause instanceof Error?cause.message:"تعذر تحميل مهام الطالب");}finally{setLoading(false)}},[]);
 useEffect(()=>{void load(id)},[id,load]);
 async function toggleTask(taskId:string){setBusy(taskId);try{const query=id?`?studentId=${encodeURIComponent(id)}`:"";const response=await fetch(`/api/student/learning${query}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({taskId})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||"تعذر حفظ الإنجاز");await load(id);}catch(cause){window.alert(cause instanceof Error?cause.message:"تعذر حفظ الإنجاز")}finally{setBusy("")}}
 const student=bundle?.student; const first=student?.name?.split(" ")[0]||"أحمد"; const stars=Math.min(30,bundle?.valueStars?.length??0); const subj=[{n:"الإملاء والخط",i:"🖊️",p:90},{n:"لغتي",i:"📘",p:92},{n:"الدراسات الإسلامية",i:"🕌",p:88},{n:"القرآن الكريم",i:"📖",p:95}];
 return <main className="ref-page ref-student"><header className="ref-student-hero"><div className="ref-student-head"><div className="ref-student-welcome">☀️ مرحبًا {first}<br/><small>الصف الثاني / 4</small></div><div className="ref-student-brand">📖 تعلّمت<br/><small>معًا نصنع جيلًا أفضل</small></div></div><div className="ref-shaka-top">🤖</div></header>
 <section className="ref-card ref-student-profile"><div className="ref-profile-grid"><div className="ref-profile-main"><div className="ref-child-avatar">👦🏻</div><div><span>👤 ملف الطالب</span><h2>{first}</h2><b>الصف الثاني / 4</b><div className="ref-bubble">أتعلم<br/>وأصنع مستقبلي المشرق! ☀️</div></div></div><div><div className="ref-star-today"><i>⭐</i><div><b>نجمي اليوم</b><br/><strong>{stars} / 30</strong><div className="ref-progress"><span style={{width:`${stars/30*100}%`,background:'#14bd6b'}}/></div></div></div><div className="ref-tags"><div>💚 <b>هواياتي</b><br/><small>القراءة　الرسم</small></div><div>🏆 <b>إنجازاتي</b><br/><small>قارئ مميز　متعاون</small></div></div></div></div></section>
 <section id="subjects" className="ref-subjects">{subj.map(s=><div className="ref-card ref-subject" key={s.n}><i>{s.i}</i><b>{s.n}</b><strong>{s.p}%</strong><div className="ref-progress"><span style={{width:`${s.p}%`,background:s.n==='الإملاء والخط'?'#9c48ea':s.n==='لغتي'?'#258bea':'#16bd73'}}/></div></div>)}</section>
 <section className="ref-today">
  <div id="today" className="ref-card ref-panel"><h3>📋 مهامي اليوم</h3>{loading&&!bundle?<p>جاري تجهيز مهام اليوم…</p>:null}{error?<p style={{padding:10,borderRadius:12,background:'#fff4e8'}}>المحتوى غير مكتمل أو تعذر الاتصال: {error}</p>:null}{bundle?.today.tasks.length?bundle.today.tasks.map(task=>{const completed=task.status==='COMPLETED';return <div className="ref-task" key={task.id} style={{alignItems:'center'}}><button type="button" aria-pressed={completed} disabled={busy===task.id} onClick={()=>void toggleTask(task.id)} style={{width:46,height:46,borderRadius:'50%',border:completed?'2px solid #18a766':'2px solid #cbd7d0',background:completed?'#e9f8f0':'#fff',color:completed?'#127846':'#7a8a82',fontWeight:800,flex:'0 0 auto',cursor:'pointer'}}>{completed?'تم':'○'}</button><span style={{flex:1}}><b>{task.subject}</b><br/><strong>{task.taskText}</strong><br/><small>{task.lesson}{task.skill?` · ${task.skill}`:''}</small></span></div>}):(!loading&&!error?<p>لا توجد مهام منشورة لهذا اليوم.</p>:null)}{bundle?.today.incompleteSubjects.length?<small style={{display:'block',marginTop:8}}>المحتوى غير مكتمل: {bundle.today.incompleteSubjects.join('، ')}</small>:null}</div>
  <div id="week" className="ref-card ref-panel"><h3>🗓️ هذا الأسبوع</h3>{bundle?.week?bundle.week.days.map(day=><details key={day.date} style={{borderBottom:'1px solid #edf0ee',padding:'8px 0'}}><summary style={{cursor:'pointer',fontWeight:800}}>{day.day}</summary>{day.subjects.map(item=><div key={item.id} style={{padding:'7px 4px'}}><b>{item.subject}</b><br/><small>{item.lesson}</small>{item.expectedTask?<small style={{display:'block'}}>المطلوب: {item.expectedTask}</small>:null}{item.contentStatus==='INCOMPLETE'?<small>المحتوى غير مكتمل</small>:null}</div>)}</details>):<p>لم تُنشر خطة هذا الأسبوع بعد.</p>}</div>
 </section>
 <section className="ref-card ref-stars"><div className="ref-gift">🎁<b>مكافأة قادمة<br/>{stars} / 30</b></div><div><b>⭐ اجمع 30 نجمة لتحصل على مكافأتك!</b><div className="ref-star-grid">{Array.from({length:30},(_,i)=><span className={i<stars?'on':''} key={i}>★</span>)}</div></div><div className="ref-trophy">🏆🤖<b style={{display:'block',fontSize:16}}>نجومي ⭐</b></div></section>
 {bundle?.previewStudents&&bundle.previewStudents.length>1?<div style={{textAlign:'center',margin:10}}><select value={id||student?.id||''} onChange={e=>setId(e.target.value)}>{bundle.previewStudents.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></div>:null}
 <nav className="ref-bottom"><Link className="active" href="/student"><i>🏠</i><b>الرئيسية</b></Link><a href="#today"><i>📋</i><b>مهامي</b></a><button className="shaka" type="button" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}><i>🤖</i><b>شكابمبو</b></button><a href="#subjects"><i>📖</i><b>المواد</b></a><a href="#week"><i>🗓️</i><b>الأسبوع</b></a></nav></main>}
