"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
type S={id:string;name:string;className:string}; type B={student:S;subjects:{id:string;name:string;order:number}[];assessments:{studentId:string;level:string}[];valueStars:{id:string}[]};
export default function StudentPage(){const [students,setStudents]=useState<S[]>([]);const [bundle,setBundle]=useState<B|null>(null);const [id,setId]=useState("");
 useEffect(()=>{fetch("/api/teacher/student-preview",{cache:"no-store"}).then(r=>r.json()).then(x=>{setStudents(x.students||[]);if(x.students?.[0])setId(x.students[0].id)}).catch(()=>{})},[]);
 useEffect(()=>{if(!id)return;fetch(`/api/teacher/student-preview?studentId=${encodeURIComponent(id)}`,{cache:"no-store"}).then(r=>r.json()).then(setBundle).catch(()=>{})},[id]);
 const student=bundle?.student??students[0]; const first=student?.name?.split(" ")[0]||"أحمد"; const stars=Math.min(30,bundle?.valueStars?.length??12); const subj=[{n:"الإملاء والخط",i:"🖊️",p:90},{n:"لغتي",i:"📘",p:92},{n:"الدراسات الإسلامية",i:"🕌",p:88},{n:"القرآن الكريم",i:"📖",p:95}]; const tasks=["مراجعة سورة الكوثر","حل تدريبات الدرس الثالث","كتابة كلمات الإملاء","مذاكرة درس آداب الطعام"]; const schedule=[["القرآن الكريم","8:00 - 8:40","📖"],["لغتي","8:50 - 9:30","📘"],["الدراسات الإسلامية","10:00 - 10:40","🕌"],["الإملاء والخط","11:00 - 11:40","🖊️"]];
 return <main className="ref-page ref-student"><header className="ref-student-hero"><div className="ref-student-head"><div className="ref-student-welcome">☀️ مرحبًا {first}<br/><small>الصف الثاني / 4</small></div><div className="ref-student-brand">📖 تعلّمت<br/><small>معًا نصنع جيلًا أفضل</small></div></div><div className="ref-shaka-top">🤖</div></header>
 <section className="ref-card ref-student-profile"><div className="ref-profile-grid"><div className="ref-profile-main"><div className="ref-child-avatar">👦🏻</div><div><span>👤 ملف الطالب</span><h2>{first}</h2><b>الصف الثاني / 4</b><div className="ref-bubble">أتعلم<br/>وأصنع مستقبلي المشرق! ☀️</div></div></div><div><div className="ref-star-today"><i>⭐</i><div><b>نجمي اليوم</b><br/><strong>{stars} / 30</strong><div className="ref-progress"><span style={{width:`${stars/30*100}%`,background:'#14bd6b'}}/></div></div></div><div className="ref-tags"><div>💚 <b>هواياتي</b><br/><small>القراءة　الرسم</small></div><div>🏆 <b>إنجازاتي</b><br/><small>قارئ مميز　متعاون</small></div></div></div></div></section>
 <section className="ref-subjects">{subj.map(s=><div className="ref-card ref-subject" key={s.n}><i>{s.i}</i><b>{s.n}</b><strong>{s.p}%</strong><div className="ref-progress"><span style={{width:`${s.p}%`,background:s.n==='الإملاء والخط'?'#9c48ea':s.n==='لغتي'?'#258bea':'#16bd73'}}/></div></div>)}</section>
 <section className="ref-today"><div className="ref-card ref-panel"><h3>📅 جدولي اليوم</h3><div className="ref-schedule">{schedule.map((x,i)=><div className="ref-task" key={i}><span>{x[2]}</span><div><b>{x[0]}</b><br/><small>{x[1]}</small></div></div>)}</div></div><div className="ref-card ref-panel"><h3>📋 مهامي اليوم</h3>{tasks.map((t,i)=><label className="ref-task" key={t}><input type="checkbox"/><span><b>{t}</b><br/><small>{subj[i]?.n}</small></span></label>)}</div></section>
 <section className="ref-card ref-stars"><div className="ref-gift">🎁<b>مكافأة قادمة<br/>{stars} / 30</b></div><div><b>⭐ اجمع 30 نجمة لتحصل على مكافأتك!</b><div className="ref-star-grid">{Array.from({length:30},(_,i)=><span className={i<stars?'on':''} key={i}>★</span>)}</div></div><div className="ref-trophy">🏆🤖<b style={{display:'block',fontSize:16}}>نجومي ⭐</b></div></section>
 {students.length>1&&<div style={{textAlign:'center',margin:10}}><select value={id} onChange={e=>setId(e.target.value)}>{students.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></div>}
 <nav className="ref-bottom"><Link className="active" href="/student"><i>🏠</i><b>الرئيسية</b></Link><a href="#subjects"><i>📖</i><b>المواد</b></a><button className="shaka" type="button" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}><i>🤖</i><b>شكابمبو</b></button><Link href="/teacher/curriculum"><i>📖</i><b>الكتب</b></Link><Link href="/"><i>•••</i><b>المزيد</b></Link></nav></main>}
