"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {DateBar} from "@/components/DateBar";
import {guardianLogin,guardianLogout,guardianMe,guardianSearch,guardianSendFollowUp,guardianSendMessage,type GuardianSearchStudent} from "@/lib/guardian-api";
import {academicWeek,plansForWeek} from "@/lib/schedule";
import type {FollowUpCategory,LearningResource,MasteryLevel,Message,Skill,SkillAssessment,SpecialFollowUp,Subject,Term,ValueStar,ValueTarget,WeeklyPlan} from "@/lib/types";
const labels:Record<MasteryLevel,string>={mastered:"متقن",partial:"أتقن البعض",needs_training:"يحتاج تدريب"};
const order=["لغتي","القرآن الكريم","الدراسات الإسلامية"];
const asset="https://raw.githubusercontent.com/tssjiil-max/taallamt-download/345c9caacaa109e3e6a5022617211e0475203f4a/public/education-icons/";
const subjectIcon=(n:string)=>n.includes("لغتي")?asset+"pencil.webp":asset+"book.webp";
type Profile={preferredName?:string;photoDataUrl?:string;learningDifficulties?:string};
type Bundle={student:{id:string;name:string;className:string;subjectLevels:Record<string,MasteryLevel>};profile:Profile|null;activeTerm:Term|null;subjects:Subject[];weeklyPlans:WeeklyPlan[];skills:Skill[];assessments:SkillAssessment[];resources:Array<Omit<LearningResource,"answerGuide">>;values:ValueTarget[];valueStars:ValueStar[];followUp:SpecialFollowUp|null;messages:Message[]};
function errText(e:unknown){const p=(e as {payload?:{error?:string}})?.payload;if(p?.error==="INVALID_CODE")return"رمز الوصول غير صحيح.";if(p?.error==="DEVICE_LIMIT")return"تم الوصول للحد المسموح من الأجهزة.";return"تعذر تسجيل الدخول الآن."}
export default function GuardianPage(){
 const [bundle,setBundle]=useState<Bundle|null>(null),[ready,setReady]=useState(false),[search,setSearch]=useState(""),[matches,setMatches]=useState<GuardianSearchStudent[]>([]),[selected,setSelected]=useState(""),[code,setCode]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[statement,setStatement]=useState(""),[category,setCategory]=useState<FollowUpCategory>("learning"),[notice,setNotice]=useState("");
 const refresh=async()=>{const b=await guardianMe<Bundle>();setBundle(b);return b};
 useEffect(()=>{guardianMe<Bundle>().then(setBundle).catch(()=>{}).finally(()=>setReady(true))},[]);
 useEffect(()=>{if(bundle||search.trim().length<2){setMatches([]);return}const t=setTimeout(()=>guardianSearch(search.trim()).then(r=>setMatches(r.students)).catch(()=>setMatches([])),250);return()=>clearTimeout(t)},[search,bundle]);
 async function login(e:FormEvent){e.preventDefault();if(!selected||!/^[0-9]{6}$/.test(code))return;setBusy(true);setError("");try{await guardianLogin(selected,code);await refresh()}catch(x){setError(errText(x))}finally{setBusy(false)}}
 async function logout(){setBusy(true);try{await guardianLogout()}catch{}setBundle(null);setBusy(false)}
 async function send(e:FormEvent){e.preventDefault();if(!message.trim())return;setBusy(true);try{await guardianSendMessage(message.trim());setMessage("");await refresh();setNotice("تم إرسال الرسالة للمعلم.")}finally{setBusy(false)}}
 async function follow(e:FormEvent){e.preventDefault();if(!statement.trim())return;setBusy(true);try{await guardianSendFollowUp(category,statement.trim());setStatement("");await refresh();setNotice("تم إرسال الملاحظة للمعلم.")}finally{setBusy(false)}}
 if(!ready)return <main className="shell"><div className="empty-state">جاري فتح بوابة ولي الأمر…</div></main>;
 if(!bundle)return <main className="shell guardian-shell"><header className="guardian-login-header"><div className="teacher-brand-block"><div className="brand-mark">ت</div><div><h1>تعلّمت</h1><p>متابعة ولي الأمر</p></div></div></header><DateBar/><section className="ui-section first-ui-section"><div className="section-title-row"><div><h2>دخول ولي الأمر</h2><p>ابحث عن الطالب ثم أدخل رمز الوصول.</p></div></div><form className="card stack" onSubmit={login}><input className="field" value={search} onChange={e=>{setSearch(e.target.value);setSelected("")}} placeholder="اسم الطالب"/>{matches.map(m=><button type="button" className={`row guardian-pick ${selected===m.id?"selected":""}`} key={m.id} onClick={()=>setSelected(m.id)}><span>{m.name}</span><small>{m.className}</small></button>)}{selected&&<input className="field guardian-code" inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,"").slice(0,6))} placeholder="000000"/>}{error&&<div className="notice warn">{error}</div>}<button className="btn" disabled={busy||!selected||code.length!==6}>{busy?"جاري التحقق…":"دخول"}</button></form></section><footer className="site-credit">برمجة سلطان الصاعدي</footer></main>;
 const s=bundle.student,p=bundle.profile,subjects=bundle.subjects.filter(x=>x.enabled!==false&&order.includes(x.name)).sort((a,b)=>order.indexOf(a.name)-order.indexOf(b.name)),week=academicWeek(),weekly=plansForWeek(bundle.weeklyPlans,week),teacherMessages=bundle.messages.filter(x=>x.author==="teacher"),needs=bundle.assessments.filter(x=>x.level==="needs_training"),stars=bundle.valueStars.length,awards=Math.floor(stars/30),progress=stars%30;
 const updates=[...bundle.assessments.map(a=>({id:a.id,at:a.assessedAt,title:"تقييم جديد",detail:labels[a.level]})),...teacherMessages.map(m=>({id:m.id,at:m.createdAt,title:"رسالة من المعلم",detail:m.body})),...bundle.valueStars.map(v=>({id:v.id,at:v.awardedAt,title:"نجمة جديدة",detail:"سلوك وقيمة إيجابية"}))].sort((a,b)=>b.at.localeCompare(a.at)).slice(0,3);
 return <main className="shell guardian-shell"><header className="guardian-header"><div className="teacher-brand-block"><div className="brand-mark">ت</div><div><h1>تعلّمت</h1><p>متابعة ولي الأمر</p></div></div><button className="logout-mini" onClick={()=>void logout()} disabled={busy}>خروج</button></header><DateBar/>{notice&&<div className="notice section">{notice}</div>}
 <section className="ui-section first-ui-section"><Link href="/guardian/profile" className="student-main-card card"><div className="student-main-photo">{p?.photoDataUrl?<img src={p.photoDataUrl} alt="صورة الطالب"/>:<div className="student-placeholder">{s.name.charAt(0)}</div>}<span className="photo-edit-mark">تعديل</span></div><div className="student-main-copy"><h1>{p?.preferredName||s.name}</h1><p>{s.className}</p><small>اضغط على الصورة لتعديل الصورة وبيانات الطالب</small></div><div className="student-card-stats"><span><b>{progress}</b><small>نجمة</small></span><span><img src={asset+"trophy.webp"} alt="الجوائز"/><b>{awards}</b><small>جائزة</small></span></div></Link></section>
 <section className="ui-section rating-section"><div className="section-title-row"><div><h2>التقييم العام</h2><p>التقدم داخل الفصل والتعامل مع الزملاء</p></div><div className="award-summary"><img src={asset+"trophy.webp"} alt="الأوسمة"/><b>{awards}</b><span>الأوسمة</span></div></div><div className="thirty-stars">{Array.from({length:30},(_,i)=><span className={i<progress?"earned":""} key={i}>★</span>)}</div><p className="reward-rule">عند اكتمال 30 نجمة يحصل الطالب على جائزة، ثم يبدأ عدّ جديد.</p></section>
 <section className="ui-section"><div className="section-title-row"><div><h2>المواد والمكتبة</h2><p>آخر تقييمات المعلم</p></div></div><div className="guardian-four-grid">{subjects.map(x=><article className="guardian-big-choice" key={x.id}><img className="edu-icon" src={subjectIcon(x.name)} alt=""/><h3>{x.name}</h3><p>{s.subjectLevels[x.id]?labels[s.subjectLevels[x.id]]:"لم يقيّم"}</p></article>)}<a className="guardian-big-choice" href="#library"><img className="edu-icon" src={asset+"library.webp"} alt=""/><h3>المكتبة</h3><p>{bundle.resources.length?`${bundle.resources.length} مادة`:"لا توجد ملفات"}</p></a></div></section>
 <section className="ui-section"><div className="section-title-row"><div><h2>هذا الأسبوع</h2><p>ما يتعلمه الطالب الآن</p></div><span className="soft-chip">الأسبوع {week}</span></div><div className="week-compact-list">{weekly.map(w=>{const sub=subjects.find(x=>x.id===w.subjectId);return <div className="week-compact-row" key={w.id}><img className="mini-edu-icon" src={sub?subjectIcon(sub.name):asset+"book.webp"} alt=""/><div><b>{sub?.name||"المادة"}</b><p>{w.title}</p></div></div>})}{weekly.length===0&&<div className="empty-state compact-empty">لا توجد خطة منشورة لهذا الأسبوع.</div>}</div></section>
 <section className="ui-section"><div className="section-title-row"><div><h2>يحتاج متابعتك</h2><p>يظهر فقط ما يحتاج اهتمامًا</p></div></div>{needs.length||p?.learningDifficulties||bundle.followUp?<div className="attention-card card">{needs.length>0&&<p>توجد {needs.length} تقييمات تحتاج تدريبًا.</p>}{p?.learningDifficulties&&<p>توجد صعوبات مسجلة في إعدادات الطالب.</p>}{bundle.followUp?.goal&&<p><b>الهدف الحالي:</b> {bundle.followUp.goal}</p>}{bundle.followUp?.plan?.length?<ul>{bundle.followUp.plan.map(x=><li key={x}>{x}</li>)}</ul>:null}</div>:<div className="empty-state compact-empty">لا توجد متابعة مطلوبة حاليًا.</div>}</section>
 <section className="ui-section"><div className="section-title-row"><div><h2>الخدمات</h2></div></div><div className="guardian-services-grid"><a className="guardian-service" href="#follow"><img src={asset+"book.webp"} alt=""/><b>الخطة والمتابعة</b></a><a className="guardian-service" href="#message"><img src={asset+"pencil.webp"} alt=""/><b>رسالة المعلم</b></a></div></section>
 <section className="ui-section"><div className="section-title-row"><div><h2>آخر التحديثات</h2></div></div>{updates.length?<div className="activity-grid">{updates.map(u=><div className="activity-card" key={`${u.id}-${u.at}`}><div><h3>{u.title}</h3><p>{u.detail}</p></div></div>)}</div>:<div className="empty-state compact-empty">لا توجد تحديثات حديثة.</div>}</section>
 <section className="ui-section" id="library"><div className="section-title-row"><div><h2>المكتبة</h2></div></div>{bundle.resources.length?<div className="square-grid">{bundle.resources.map(r=><Link className="square-card" href={`/guardian/resources/${r.id}`} key={r.id}><img className="edu-icon" src={asset+"library.webp"} alt=""/><h3>{r.title}</h3><p>{r.instructions}</p></Link>)}</div>:<div className="empty-state compact-empty">لا توجد ملفات منشورة حاليًا.</div>}</section>
 <section className="ui-section" id="message"><div className="section-title-row"><div><h2>رسالة المعلم</h2></div></div><div className="card stack">{bundle.messages.slice(-5).map(m=><div className="message-mini" key={m.id}><b>{m.author==="teacher"?"المعلم":"ولي الأمر"}</b><p>{m.body}</p></div>)}<form className="stack" onSubmit={send}><input className="field" value={message} onChange={e=>setMessage(e.target.value)} placeholder="اكتب رسالة قصيرة للمعلم"/><button className="btn" disabled={busy}>إرسال</button></form></div></section>
 <section className="ui-section" id="follow"><div className="section-title-row"><div><h2>الخطة والمتابعة</h2><p>أرسل صعوبة أو ملاحظة ليضع المعلم الهدف والخطة المناسبة.</p></div></div>{bundle.followUp?.goal&&<div className="card"><h3>{bundle.followUp.goal}</h3>{bundle.followUp.plan?.length?<ul>{bundle.followUp.plan.map(x=><li key={x}>{x}</li>)}</ul>:null}</div>}<form className="card stack section" onSubmit={follow}><select className="field" value={category} onChange={e=>setCategory(e.target.value as FollowUpCategory)}><option value="learning">صعوبة تعليمية</option><option value="behavior">متابعة سلوكية</option><option value="health">حالة صحية مؤثرة</option><option value="family">ظرف أسري مؤثر</option><option value="other">أخرى</option></select><textarea className="field textarea" value={statement} onChange={e=>setStatement(e.target.value)} placeholder="اكتب ما يحتاج المعلم معرفته…"/><button className="btn" disabled={busy}>إرسال للمعلم</button></form></section>
 <footer className="site-credit">برمجة سلطان الصاعدي</footer><nav className="bottom-nav guardian-bottom-nav"><Link className="bottom-nav-item active" href="/guardian"><b>الرئيسية</b></Link><a className="bottom-nav-item" href="#library"><b>المكتبة</b></a><a className="bottom-nav-item" href="#message"><b>الرسائل</b></a></nav></main>
}