"use client";
import Link from "next/link";
import {DateBar} from "@/components/DateBar";
import {NotificationPanel} from "@/components/NotificationPanel";
import {academicWeek} from "@/lib/schedule";
import {useTaallamt} from "@/lib/store";
const order=["لغتي","القرآن الكريم","الدراسات الإسلامية"];
const icons="/guardian-icons/";
const subjectIcon=(n:string)=>n.includes("لغتي")?icons+"lughati.svg":n.includes("قرآن")?icons+"quran.svg":icons+"islamic.svg";
export default function TeacherHome(){
 const store=useTaallamt(),term=store.terms.find(x=>x.active)??store.terms[0],students=store.students.filter(x=>x.active),week=academicWeek();
 const subjects=store.subjects.filter(x=>x.enabled&&x.termId===term?.id&&order.includes(x.name)).sort((a,b)=>order.indexOf(a.name)-order.indexOf(b.name));
 const guardianMessages=store.messages.filter(x=>x.author==="guardian").length,needsReview=Object.values(store.followUps).filter(x=>x.status==="needs_review").length;
 const awards=Math.floor(store.valueStars.length/30);
 const recent=[...store.assessments.map(x=>({id:x.id,at:x.assessedAt,title:"تقييم طالب",detail:store.skills.find(s=>s.id===x.skillId)?.category||"تقييم مهارة"})),...store.messages.filter(x=>x.author==="guardian").map(x=>({id:x.id,at:x.createdAt,title:"رسالة ولي أمر",detail:x.body})),...store.valueStars.map(x=>({id:x.id,at:x.awardedAt,title:"نجمة سلوك",detail:store.values.find(v=>v.id===x.valueId)?.title||"قيمة إيجابية"}))].filter(x=>x.at).sort((a,b)=>b.at.localeCompare(a.at)).slice(0,4);
 return <main className="shell teacher-home-shell teacher-dashboard">
  <header className="teacher-hero"><div className="teacher-hero-copy"><div className="teacher-brand-block"><div className="brand-mark">ت</div><div><h1>تعلّمت</h1><p>معًا نصنع مستقبلهم</p></div></div><div className="teacher-greeting"><small>صباح الخير</small><h2>أ. سلطان الصاعدي</h2><p>الصف الثاني / 4 · الأسبوع {week}</p></div></div><Link className="shak-hero" href="/teacher/shakabumbo"><img src="/shakabumbo.jpg" alt="شكابمبو"/><span>شكابمبو</span><small>مساعد المعلم</small></Link></header>
  <div className="teacher-date"><DateBar/></div>
  <section className="ui-section teacher-metrics"><div className="teacher-metric"><b>{students.length}</b><span>طلاب الفصل</span></div><div className="teacher-metric"><b>{store.valueStars.length}</b><span>نجوم السلوك</span></div><div className="teacher-metric"><b>{guardianMessages+needsReview}</b><span>التنبيهات</span></div><div className="teacher-metric"><b>{awards}</b><span>الجوائز</span></div></section>
  <section className="ui-section"><div className="section-title-row"><div><h2>المواد الدراسية</h2><p>الوصول المباشر للمادة وخطتها</p></div></div><div className="teacher-subject-grid">{subjects.map((s,i)=>{const plan=store.weeklyPlans.find(x=>x.termId===term?.id&&x.subjectId===s.id&&x.week===week);return <Link className={`teacher-subject subject-${i+1}`} href={`/teacher/subject/${s.id}`} key={s.id}><img src={subjectIcon(s.name)} alt=""/><div><h3>{s.name}</h3><p>{plan?.title||"لا توجد خطة منشورة"}</p><span>عرض التفاصيل</span></div></Link>})}</div></section>
  <section className="ui-section"><div className="section-title-row"><div><h2>الخدمات السريعة</h2><p>أهم أدوات الحصة اليومية</p></div></div><div className="teacher-quick-grid"><Link href="/teacher/values" className="teacher-quick"><img src={icons+"trophy.svg"} alt=""/><b>السلوك</b><small>القيم والنجوم</small></Link><Link href="/teacher/assessment" className="teacher-quick"><img src={icons+"followup.svg"} alt=""/><b>التقييم</b><small>تقييم المهارات</small></Link><Link href="/teacher/students" className="teacher-quick"><img src={icons+"message.svg"} alt=""/><b>أولياء الأمور</b><small>{guardianMessages?`${guardianMessages} رسالة`:"لا توجد رسائل"}</small></Link><Link href="/teacher/library" className="teacher-quick"><img src={icons+"library.svg"} alt=""/><b>المكتبة</b><small>المحتوى التعليمي</small></Link></div></section>
  <section className="ui-section"><div className="section-title-row"><div><h2>آخر النشاطات</h2><p>من سجلات النظام الحقيقية</p></div></div>{recent.length?<div className="activity-grid">{recent.map(x=><article className="activity-card" key={`${x.id}-${x.at}`}><h3>{x.title}</h3><p>{x.detail}</p></article>)}</div>:<div className="empty-state compact-empty">لا توجد نشاطات حديثة.</div>}</section>
  <section className="ui-section"><div className="section-title-row"><div><h2>أدوات المعلم</h2></div></div><div className="teacher-tools"><Link href="/teacher/portfolio">ملف الإنجاز</Link><Link href="/teacher/announcements">الإعلانات</Link><Link href="/teacher/reports">التقارير</Link><Link href="/teacher/distribution">التوزيع الأسبوعي</Link></div></section>
  <details className="utility-panel"><summary>الإشعارات والإعدادات</summary><NotificationPanel role="teacher"/><div className="teacher-settings-links"><Link href="/teacher/settings">إدارة الفصل</Link><Link href="/teacher/data-exchange">البيانات</Link><Link href="/teacher/backend">الربط الخلفي</Link></div></details>
  <footer className="site-credit">برمجة سلطان الصاعدي</footer><nav className="bottom-nav teacher-bottom-nav"><Link className="bottom-nav-item active" href="/"><b>الرئيسية</b></Link><Link className="bottom-nav-item" href="/teacher/students"><b>الطلاب</b></Link><Link className="bottom-nav-item" href="/teacher/library"><b>المكتبة</b></Link><Link className="bottom-nav-item" href="/teacher/shakabumbo"><b>شكابمبو</b></Link></nav>
 </main>
}