"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {PrintButton} from "@/components/PrintButton";
import {ShareButton} from "@/components/ShareButton";
import {TeacherBackHeader,TeacherNav} from "@/components/TeacherChrome";
import {useTaallamt} from "@/lib/store";

const sections=["البيانات المهنية","التخطيط","تنفيذ التدريس","استراتيجيات التدريس","التقويم","تحليل النتائج","متابعة تعلم الطلاب","الخطط العلاجية","الإثراء","الفروق الفردية","إدارة الصف","القيم والسلوك","توظيف التقنية","مصادر التعلم","التواصل والشراكة مع الأسرة","الأنشطة والمبادرات","التطوير المهني","الإنجازات","الشواهد والمرفقات"];
type Evidence={id:string;title:string;section:string;source:string;date:string;fileName?:string;automatic?:boolean};
type Profile={teacher:string;school:string;principal:string;className:string;term:string;year:string;specialization:string;phone:string;email:string};
const fixed:Profile={teacher:"سلطان الصاعدي",school:"مدرسة عمرو بن أوس الثقفي",principal:"تركي عبدالعزيز الحجيلي",className:"الصف الثاني / 4",term:"الفصل الدراسي الأول",year:"1448هـ",specialization:"",phone:"",email:""};

export default function PortfolioPage(){
 const store=useTaallamt(),[profile,setProfile]=useState(fixed),[evidence,setEvidence]=useState<Evidence[]>([]),[title,setTitle]=useState(""),[section,setSection]=useState(sections[0]),[fileName,setFileName]=useState(""),[editing,setEditing]=useState(false);
 useEffect(()=>{try{const p=localStorage.getItem("taallamt-teacher-profile"),e=localStorage.getItem("taallamt-portfolio-evidence");if(p)setProfile({...fixed,...JSON.parse(p)});if(e)setEvidence(JSON.parse(e))}catch{}},[]);
 const automatic=useMemo<Evidence[]>(()=>[
  ...store.resources.map(item=>({id:`resource:${item.id}`,title:item.title,section:item.kind==="worksheet"||item.kind==="skills_practice"?"مصادر التعلم":"التقويم",source:"المكتبة",date:item.createdAt,automatic:true})),
  ...Object.values(store.followUps).map(item=>({id:`follow:${item.studentId}`,title:`متابعة وخطة للطالب ${store.students.find(s=>s.id===item.studentId)?.name??""}`,section:"الخطط العلاجية",source:"ملف الطالب",date:new Date().toISOString(),automatic:true})),
  ...store.messages.filter(item=>item.author==="teacher").map(item=>({id:`message:${item.id}`,title:"تواصل موثق مع ولي أمر",section:"التواصل والشراكة مع الأسرة",source:"التواصل",date:item.createdAt,automatic:true})),
  ...store.behaviorEvaluations.map(item=>({id:`behavior:${item.id}`,title:"تقييم سلوك وقيمة تربوية",section:"القيم والسلوك",source:"السلوك والتحفيز",date:item.evaluatedAt,automatic:true})),
 ],[store.resources,store.followUps,store.messages,store.behaviorEvaluations,store.students]);
 const all=[...automatic,...evidence],covered=new Set(all.map(item=>item.section)),completion=Math.round(covered.size/sections.length*100);
 function saveProfile(event:FormEvent){event.preventDefault();localStorage.setItem("taallamt-teacher-profile",JSON.stringify(profile));setEditing(false)}
 function addEvidence(event:FormEvent){event.preventDefault();if(!title.trim())return;const next=[{id:crypto.randomUUID(),title:title.trim(),section,source:"إضافة المعلم",date:new Date().toISOString(),fileName:fileName||undefined},...evidence];setEvidence(next);localStorage.setItem("taallamt-portfolio-evidence",JSON.stringify(next));setTitle("");setFileName("")}
 function remove(id:string){const next=evidence.filter(item=>item.id!==id);setEvidence(next);localStorage.setItem("taallamt-portfolio-evidence",JSON.stringify(next))}
 return <main className="shell inner-shell"><TeacherBackHeader title="ملف إنجاز المعلم" subtitle="يتعبأ تلقائيًا من أعمالك اليومية" icon="م"/>
 <section className="inner-section portfolio-cover"><div><small>ملف الإنجاز المهني</small><h2>{profile.teacher}</h2><p>{profile.school} · {profile.className}</p><p>مدير المدرسة: {profile.principal}</p></div><div className="portfolio-progress"><b>{completion}%</b><span>اكتمال الملف</span></div></section>
 <section className="inner-section no-print"><div className="inner-section-head"><div><h2>البيانات المعتمدة</h2><span>يمكنك تعديلها متى احتجت</span></div><button className="btn secondary" onClick={()=>setEditing(value=>!value)}>{editing?"إلغاء":"تعديل"}</button></div>{editing?<form className="stack" onSubmit={saveProfile}>{Object.entries(profile).map(([key,value])=><label className="stack" key={key}><span>{{teacher:"اسم المعلم",school:"المدرسة",principal:"مدير المدرسة",className:"الصف والفصل",term:"الفصل الدراسي",year:"العام",specialization:"التخصص",phone:"الجوال",email:"البريد"}[key as keyof Profile]}</span><input className="field" value={value} onChange={event=>setProfile({...profile,[key]:event.target.value})}/></label>)}<button className="btn">حفظ البيانات</button></form>:<div className="profile-facts"><span><small>المعلم</small><b>{profile.teacher}</b></span><span><small>المدرسة</small><b>{profile.school}</b></span><span><small>مدير المدرسة</small><b>{profile.principal}</b></span><span><small>الصف</small><b>{profile.className}</b></span></div>}</section>
 <section className="inner-section no-print"><div className="inner-section-head"><div><h2>إضافة شاهد</h2><span>الأعمال المناسبة تضاف تلقائيًا؛ استخدم هذا للنواقص فقط</span></div></div><form className="stack" onSubmit={addEvidence}><input className="field" required value={title} onChange={e=>setTitle(e.target.value)} placeholder="عنوان الشاهد أو العمل"/><select className="field" value={section} onChange={e=>setSection(e.target.value)}>{sections.map(item=><option key={item}>{item}</option>)}</select><label className="field">إرفاق ملف<input type="file" onChange={e=>setFileName(e.target.files?.[0]?.name??"")}/></label><button className="btn">إضافة إلى ملف الإنجاز</button></form></section>
 <section className="inner-section"><div className="inner-section-head"><div><h2>أقسام الملف</h2><span>{covered.size} من {sections.length} أقسام لديها شواهد</span></div><div className="mini-actions no-print"><PrintButton label="PDF / طباعة"/><ShareButton title="ملف إنجاز المعلم سلطان الصاعدي" text="ملف إنجاز المعلم — يتضمن أسماء الطلاب في الشواهد المختارة"/></div></div><div className="portfolio-sections">{sections.map(item=>{const count=all.filter(e=>e.section===item).length;return <article className={count?"complete":""} key={item}><span>{count?"✓":"○"}</span><div><b>{item}</b><small>{count?`${count} شاهد محفوظ`:"يحتاج شاهدًا"}</small></div></article>})}</div></section>
 <section className="inner-section"><div className="inner-section-head"><h2>الشواهد المجمعة</h2><span>{all.length}</span></div><div className="list">{all.map(item=><div className="row" key={item.id}><div><h4>{item.title}</h4><small>{item.section} · {item.source}{item.fileName?` · ${item.fileName}`:""}</small></div>{item.automatic?<span className="badge">تلقائي</span>:<button className="btn danger no-print" onClick={()=>remove(item.id)}>حذف</button>}</div>)}{!all.length&&<div className="empty-state">سيبدأ النظام جمع الشواهد مع أول عمل تحفظه.</div>}</div></section>
 <div className="notice warn no-print">عند المشاركة الخارجية ستظهر أسماء الطلاب الموجودة في الشواهد، حسب اختيارك.</div><footer className="site-credit">برمجة سلطان الصاعدي</footer><TeacherNav/></main>
}
