"use client";
import Link from "next/link";
import {useMemo,useState} from "react";
import {academicWeek} from "@/lib/schedule";
import {useTaallamt} from "@/lib/store";
import type {MasteryLevel} from "@/lib/types";
const levels:MasteryLevel[]=["mastered","needs_training"],labels:Record<MasteryLevel,string>={mastered:"أتقن",partial:"يحتاج تدريب",needs_training:"يحتاج تدريب"};
function latest(a:ReturnType<typeof useTaallamt>["assessments"],studentId:string,skillId:string){const found=a.filter(x=>x.studentId===studentId&&x.skillId===skillId).at(-1)?.level;return found==="partial"?"needs_training":found}
export default function AssessmentPage(){
 const store=useTaallamt(),term=store.terms.find(t=>t.active)??store.terms[0],subjects=store.subjects.filter(s=>s.enabled&&s.termId===term?.id).sort((a,b)=>a.order-b.order);
 const[subjectId,setSubjectId]=useState(subjects[0]?.id??"quran"),[week,setWeek]=useState(academicWeek()),[skillId,setSkillId]=useState(""),[saving,setSaving]=useState(""),[notice,setNotice]=useState("");
 const skills=store.skills.filter(s=>s.active&&s.termId===term?.id&&s.subjectId===subjectId&&s.week===week),skill=skills.find(s=>s.id===skillId)??skills[0],students=store.students.filter(s=>s.active);
 const stats=useMemo(()=>{if(!skill)return{mastered:0,needs:0,pending:students.length};const values=students.map(s=>latest(store.assessments,s.id,skill.id));return{mastered:values.filter(x=>x==="mastered").length,needs:values.filter(x=>x==="needs_training").length,pending:values.filter(x=>!x).length}},[skill,students,store.assessments]);
 async function persist(studentId:string,level:MasteryLevel){if(!skill)return;const response=await fetch("/api/teacher/assessments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({studentId,skillId:skill.id,level})});if(!response.ok)throw new Error("save");store.setSkillAssessment(studentId,skill.id,level)}
 async function save(studentId:string,level:MasteryLevel){if(!skill)return;setSaving(`${studentId}:${skill.id}`);setNotice("");try{await persist(studentId,level);setNotice(level==="mastered"?"تم حفظ «أتقن».":"تم الحفظ وإضافة الطالب للمتابعة.")}catch{setNotice("تعذر حفظ التقييم. أعد المحاولة.")}finally{setSaving("")}}
 async function applyToAll(){if(!skill||!confirm("تسجيل «أتقن» لجميع الطلاب؟ بعد الحفظ عدّل فقط من يحتاج تدريبًا."))return;setSaving("all");setNotice("");try{for(const student of students)await persist(student.id,"mastered");setNotice("تم تسجيل «أتقن» للجميع. عدّل الاستثناءات فقط.")}catch{setNotice("توقف الحفظ قبل اكتماله. راجع النتائج ثم أعد المحاولة.")}finally{setSaving("")}}
 return <main className="shell inner-shell"><header className="subject-hero"><img src="/guardian-icons/followup.svg" alt=""/><div><span className="inner-kicker">تعلّمت · الصف الثاني / 4</span><h1>التقييم السريع</h1><p>مهارتان واضحتان: أتقن أو يحتاج تدريبًا</p></div><Link className="inner-home" href="/">الرئيسية</Link></header>
 <section className="subject-stat-strip"><span><b>{stats.mastered}</b>أتقن</span><span><b>{stats.needs}</b>يحتاج تدريب</span><span><b>{stats.pending}</b>لم يقيّم</span></section>{notice&&<div className="notice">{notice}</div>}
 <section className="inner-section assessment-picker"><div className="picker-block"><h2>1. المادة</h2><div className="subject-choice-row">{subjects.map(s=><button className={subjectId===s.id?"active":""} key={s.id} onClick={()=>{setSubjectId(s.id);setSkillId("")}}>{s.name}</button>)}</div></div><div className="picker-block"><h2>2. الأسبوع</h2><div className="week-pills">{Array.from({length:17},(_,i)=>i+1).map(n=><button className={week===n?"active":""} key={n} onClick={()=>{setWeek(n);setSkillId("")}}>{n}</button>)}</div></div><div className="picker-block"><h2>3. مهارة الدرس</h2>{skills.length?<div className="assessment-skill-grid">{skills.map(s=><button className={skill?.id===s.id?"active":""} key={s.id} onClick={()=>setSkillId(s.id)}><strong>{s.category}</strong><span>{s.title}</span></button>)}</div>:<div className="empty-state">لا توجد مهارة لهذه المادة في الأسبوع {week}.</div>}</div></section>
 <section className="inner-section"><div className="inner-section-head"><div><h2>{skill?`تقييم: ${skill.category}`:"تقييم الطلاب"}</h2><span>{students.length} طالبًا</span></div>{skill&&<button className="btn" disabled={saving==="all"} onClick={()=>void applyToAll()}>تحديد الجميع: أتقن</button>}</div>{skill?<div className="clean-eval-list">{students.map((student,index)=>{const value=latest(store.assessments,student.id,skill.id),rowSaving=saving===`${student.id}:${skill.id}`;return <article key={student.id}><span className="student-number">{index+1}</span><div className="eval-name"><h3>{student.name}</h3><small>{rowSaving?"جاري الحفظ…":value?labels[value]:"لم يقيّم بعد"}</small></div><div className="eval-choice">{levels.map(level=><button className={value===level?`active ${level}`:""} disabled={rowSaving||saving==="all"} key={level} onClick={()=>void save(student.id,level)}>{labels[level]}</button>)}</div></article>})}</div>:<div className="empty-state">اختر مهارة أولًا.</div>}</section><footer className="site-credit">برمجة سلطان الصاعدي</footer></main>
}
