import { collection,deleteDoc,doc,getDoc,getDocs,query,setDoc,where } from 'firebase/firestore';
import { firebaseDb } from './client';
import { paths } from '../firestore/schema';
import type { ComprehensiveAssessment,CurriculumTarget,PortfolioEvent,RemediationPlan,Student } from '../../core/domain';
import type { Homework,HomeworkEvidence } from '../../core/homework';
import type { CurriculumRepository,LearningRepository,StudentRepository } from '../../core/ports';
import type { ClassSession,TimetableEntry,WeeklyPlanItem } from '../../core/session';
export class FirestoreStudentRepository implements StudentRepository{constructor(private workspaceId:string){}async listActive(){const s=await getDocs(query(collection(firebaseDb(),paths.students(this.workspaceId)),where('active','==',true)));return s.docs.map(d=>d.data() as Student)}async get(id:string){const s=await getDoc(doc(firebaseDb(),paths.students(this.workspaceId),id));return s.exists()?s.data() as Student:null}async save(v:Student){await setDoc(doc(firebaseDb(),paths.students(this.workspaceId),v.id),v,{merge:true})}async archive(id:string){await setDoc(doc(firebaseDb(),paths.students(this.workspaceId),id),{active:false,archivedAt:new Date().toISOString()},{merge:true})}async delete(id:string){await deleteDoc(doc(firebaseDb(),paths.students(this.workspaceId),id))}}
export class FirestoreCurriculumRepository implements CurriculumRepository{constructor(private workspaceId:string){}async listTargets(subject?:CurriculumTarget['subject']){const ref=collection(firebaseDb(),paths.curriculum(this.workspaceId));const s=await getDocs(subject?query(ref,where('subject','==',subject)):ref);return s.docs.map(d=>d.data() as CurriculumTarget)}async saveTargets(items:CurriculumTarget[]){await Promise.all(items.map(v=>setDoc(doc(firebaseDb(),paths.curriculum(this.workspaceId),v.id),v,{merge:true})))}}
export class FirestoreLearningRepository implements LearningRepository{constructor(private workspaceId:string){}private async byStudent<T>(path:string,id:string){const s=await getDocs(query(collection(firebaseDb(),path),where('studentId','==',id)));return s.docs.map(d=>d.data() as T)}async getSession(id:string){const s=await getDoc(doc(firebaseDb(),paths.sessions(this.workspaceId),id));return s.exists()?s.data() as ClassSession:null}async saveSession(v:ClassSession){await setDoc(doc(firebaseDb(),paths.sessions(this.workspaceId),v.id),v,{merge:true})}async saveAssessment(v:ComprehensiveAssessment){await setDoc(doc(firebaseDb(),paths.assessments(this.workspaceId),v.id),v,{merge:false})}listStudentAssessments(id:string){return this.byStudent<ComprehensiveAssessment>(paths.assessments(this.workspaceId),id)}async saveRemediation(v:RemediationPlan){await setDoc(doc(firebaseDb(),paths.remediation(this.workspaceId),v.id),v,{merge:true})}listStudentRemediation(id:string){return this.byStudent<RemediationPlan>(paths.remediation(this.workspaceId),id)}async appendPortfolio(items:PortfolioEvent[]){await Promise.all(items.map(v=>setDoc(doc(firebaseDb(),paths.portfolio(this.workspaceId),v.id),v,{merge:true})))}listStudentPortfolio(id:string){return this.byStudent<PortfolioEvent>(paths.portfolio(this.workspaceId),id)}async listTimetable(classId:string){const s=await getDocs(query(collection(firebaseDb(),paths.timetable(this.workspaceId)),where('classId','==',classId)));return s.docs.map(d=>d.data() as TimetableEntry)}async listWeeklyPlan(weekKey:string){const s=await getDocs(query(collection(firebaseDb(),paths.weeklyPlan(this.workspaceId)),where('weekKey','==',weekKey)));return s.docs.map(d=>d.data() as WeeklyPlanItem)}async saveWeeklyPlan(v:WeeklyPlanItem){await setDoc(doc(firebaseDb(),paths.weeklyPlan(this.workspaceId),v.id),v,{merge:true})}async saveHomework(v:Homework){await setDoc(doc(firebaseDb(),paths.homework(this.workspaceId),v.id),v,{merge:true})}async listHomework(classId:string){const s=await getDocs(query(collection(firebaseDb(),paths.homework(this.workspaceId)),where('classId','==',classId)));return s.docs.map(d=>d.data() as Homework)}async saveHomeworkEvidence(v:HomeworkEvidence){await setDoc(doc(firebaseDb(),paths.homeworkEvidence(this.workspaceId),v.id),v,{merge:true})}listStudentHomeworkEvidence(studentId:string){return this.byStudent<HomeworkEvidence>(paths.homeworkEvidence(this.workspaceId),studentId)}}
