// Generates src/app/app.css from src/app/app.src.css: lengths written in design units (`12u`, one unit = 1/412 of the
// reference width) become calc(var(--u)*12). Run with --check to fail when the generated file is out of date.
import {readFileSync,writeFileSync} from 'node:fs';

const source=readFileSync(new URL('../src/app/app.src.css',import.meta.url),'utf8');
const banner='/* GENERATED by scripts/build-app-css.mjs from app.src.css — do not edit by hand. */\n';
const output=banner+source.replace(/(?<![\w#.])(-?\d*\.?\d+)u\b/g,(_,value)=>`calc(var(--u)*${value})`);
const target=new URL('../src/app/app.css',import.meta.url);
if(process.argv.includes('--check')){
  let current='';try{current=readFileSync(target,'utf8')}catch{}
  if(current!==output){console.error('src/app/app.css is out of date: run `node scripts/build-app-css.mjs`.');process.exit(1)}
  console.log('app.css is up to date.');
}else{
  writeFileSync(target,output);
  console.log(`app.css generated (${output.length} bytes).`);
}
