import { describe,expect,it } from 'vitest';
import { LearningRuntime } from './learning-runtime';
import type { ComprehensiveAssessment, CurriculumTarget, PortfolioEvent, RemediationPlan, Student } from '../core/domain';
import type { Homework,HomeworkEvidence } from '../core/homework';
import type { ClassSession, TimetableEntry, WeeklyPlanItem } from '../core/session';
describe('operational learning runtime',()=>{it('saves teacher assessment and immediately projects it to student view',async()=>{
 const students:Student[]=[{id:'s1',fullName:'طالب تجريبي',active:true,createdAt:'2026-09-11'}];const assessments:ComprehensiveAssessment[]=[];const remediation:RemediationPlan[]=[];const portfolio:PortfolioEvent[]=[];let stars=0;const rewarded=new Set<string>();
 const learning={getSession:async(_id:string):Promise<ClassSession|null>=>null,saveSession:async(_v:ClassSession)=>{},saveAssessment:async(v:ComprehensiveAssessment)=>{assessments.push(v)},listStudentAssessments:async(id:string)=>assessments.filter(a=>a.studentId===id),listStudentRemediation:async(id:string)=>remediation.filter(p=>p.studentId===id),listStudentPortfolio:async(id:string)=>portfolio.filter(p=>p.studentId===id),saveRemediation:async(v:RemediationPlan)=>{remediation.push(v)},appendPortfolio:async(v:PortfolioEvent[])=>{portfolio.push(...v)},listTimetable:async(_id:string):Promise<TimetableEntry[]>=>[],listWeeklyPlan:async(_key:string):Promise<WeeklyPlanItem[]>=>[],saveWeeklyPlan:async(_v:WeeklyPlanItem)=>{},saveHomework:async(_v:Homework)=>{},listHomework:async(_id:string):Promise<Homework[]>=>[],saveHomeworkEvidence:async(_v:HomeworkEvidence)=>{},listStudentHomeworkEvidence:async(_id:string):Promise<HomeworkEvidence[]>=>[]};
 const runtime=new LearningRuntime({students:{listActive:async()=>students,get:async()=>students[0],save:async()=>{},archive:async()=>{},delete:async()=>{}},curriculum:{listTargets:async():Promise<CurriculumTarget[]>=>[{id:'skill',subject:'arabic',title:'مهارة'}],saveTargets:async()=>{}},learning,rewards:{getMonthlyStars:async()=>stars,applyAssessmentStars:async(_id,_m,assessmentId,n)=>{if(rewarded.has(assessmentId))return 0;rewarded.add(assessmentId);const earned=Math.min(n,30-stars);stars+=earned;return earned}},studentLive:{assessments:async()=>assessments,remediation:async()=>remediation,portfolio:async()=>portfolio,stars:async()=>stars}});
 const a:ComprehensiveAssessment={id:'a1',studentId:'s1',classSessionId:'c1',sessionDate:'2026-09-11',enteredAt:'2026-09-11T08:00:00',track:'general',academic:[{targetId:'skill',result:'mastered'}],behavior:[]};await runtime.saveAssessments([a]);const view=await runtime.studentView('s1','2026-09');expect(view.latestResults).toHaveLength(1);expect(view.stars.current).toBe(1);expect(view.achievements.length).toBeGreaterThan(0);
});});
