import React from 'react';
import {createRoot} from 'react-dom/client';
import './ui.css';
type View='teacher'|'student';
const Icon=({children}:{children:string})=><span className="ico">{children}</span>;
function App(){const [view,setView]=React.useState<View>('teacher');return <main className={`app ${view}`} dir="rtl">{view==='teacher'?<Teacher goStudent={()=>setView('student')}/>:<Student goTeacher={()=>setView('teacher')}/>}</main>}
function Teacher({goStudent}:{goStudent:()=>void}){return <>
<header className="teacherHead"><div className="profile"><button className="avatar" aria-label="صفحة الطالب" onClick={goStudent}>👤</button><div><b>أ. سلطان الصاعدي</b><span>مدرسة عمرو بن أوس الثقفي</span><span>الصف: الثاني / 4</span></div></div><div className="brand"><strong>📖 تعلّمت</strong><small>معًا نصنع جيلاً أفضل</small><em>برمجة: سلطان الصاعدي</em></div></header>
<div className="datebar"><span>📅 1 سبتمبر 2026 م</span><span>📅 4 ربيع الأول 1448 هـ</span><b>🌱 كل خطوة في التعليم ... تصنع فرقًا كبيرًا</b></div>
<section className="stats"><Card i="✉️" t="رسائل جديدة" n="3"/><Card i="❗" t="يحتاجون متابعة" n="6"/><Card i="⭐" t="تم تقييم اليوم" n="24"/><Card i="👥" t="عدد الطلاب" n="30"/></section>
<section className="lesson"><h2>🕘 حصتي الآن</h2><div className="chips"><span>10:00 - 10:45</span><span>الحصة 3</span></div><h3>🕌 الدراسات الإسلامية</h3><p>الوحدة الثانية: أخلاق المسلم</p><p>الدرس: بر الوالدين</p><p><b>المهارات:</b> يبين صور بر الوالدين – يستنتج أثر البر في حياة المسلم</p><button className="start" onClick={()=>alert('تم بدء الحصة')}>▶ ابدأ الحصة</button></section>
<section className="quick"><Tile i="📖" t="المناهج" s="الوحدات والدروس"/><Tile i="👥" t="الطلاب" s="إدارة بيانات الطلاب"/><Tile i="☑️" t="التقييم الشامل" s="أكاديمي وسلوك"/><Tile i="💬" t="التواصل" s="رسائل أولياء الأمور"/></section>
<section className="twocol"><Panel title="📊 تقدم المنهج"><Progress t="لغتي" p="32"/><Progress t="القرآن الكريم" p="25"/><Progress t="الدراسات الإسلامية" p="28"/><Progress t="الإملاء والخط" p="30"/></Panel><Panel title="🎯 متابعة اليوم"><Row n="6" t="يحتاجون متابعة"/><Row n="18" t="ممتازون اليوم"/><Row n="4" t="لم يتم تقييمهم"/><Row n="2" t="ملاحظات سلوكية"/></Panel><Panel title="☑️ مهامي اليوم"><p>□ إدخال تقييم لغتي - الوحدة 2</p><p>□ مراجعة خطط علاجية (3 طلاب)</p><p>□ إرسال واجبات الدراسات</p></Panel><Panel title="📣 الإعلانات"><p>🔴 اجتماع أولياء الأمور يوم الأحد</p><small>2026 - 09 - 05</small></Panel></section>
<Nav teacher goStudent={goStudent}/></>}
function Student({goTeacher}:{goTeacher:()=>void}){return <>
<header className="studentHead"><div className="hello"><span className="kid">👦🏻</span><b>مرحبًا أحمد ☀️</b><span>الصف الثاني / 4</span></div><div className="mascot">👽<small>أنت رائع<br/>كل يوم خطوة للأمام 🍃</small></div><div className="brand"><strong>📖 تعلّمت</strong><small>معًا نصنع جيلاً أفضل</small></div></header>
<section className="studentCard"><h2>👤 ملف الطالب</h2><div className="studentInfo"><div className="studentPhoto">👦🏻</div><div><b className="studentName">أحمد</b><p>أتعلم<br/>وأصنع مستقبلي<br/>المشرق! ☀️</p><strong>الصف الثاني / 4</strong></div></div><div className="mini"><div><b>💚 هواياتي</b><span>القراءة　 الرسم</span></div><div><b>🏆 إنجازاتي</b><span>قارئ مميز　 متعاون</span></div></div><div className="todayStar"><b>⭐ نجمي اليوم</b><strong>12 / 30</strong><i><u style={{width:'40%'}}/></i></div></section>
<section className="subjects"><Subject i="✏️" t="الإملاء والخط" p="90"/><Subject i="📘" t="لغتي" p="92"/><Subject i="🕌" t="الدراسات الإسلامية" p="88"/><Subject i="📖" t="القرآن الكريم" p="95"/></section>
<section className="studentCols"><Panel title="📅 جدولي اليوم"><Schedule c="green" i="📖" t="القرآن الكريم" time="8:00 - 8:40"/><Schedule c="blue" i="📘" t="لغتي" time="8:50 - 9:30"/><Schedule c="yellow" i="🕌" t="الدراسات الإسلامية" time="10:00 - 10:40"/><Schedule c="purple" i="✏️" t="الإملاء والخط" time="11:00 - 11:40"/></Panel><Panel title="📋 مهامي اليوم"><Task i="📖" t="مراجعة سورة الكوثر" s="القرآن الكريم"/><Task i="📘" t="حل تدريبات الدرس الثالث" s="لغتي"/><Task i="✏️" t="كتابة كلمات الإملاء" s="الإملاء والخط"/><Task i="🕌" t="مذاكرة درس آداب الطعام" s="الدراسات الإسلامية"/></Panel></section>
<section className="starsBox"><div className="champ">👽🏆<b>نجومي ⭐</b></div><div className="starTrack"><b>⭐ اجمع 30 نجمة لتحصل على مكافأتك!</b><div className="stargrid">{Array.from({length:30},(_,i)=><span className={i<12?'on':''} key={i}>☆<small>{i+1}</small></span>)}</div></div><div className="gift">🎁<b>مكافأة قادمة</b><strong>0 / 30</strong></div></section>
<Nav goTeacher={goTeacher}/></>}
function Card({i,t,n}:{i:string,t:string,n:string}){return <article><Icon>{i}</Icon><span>{t}</span><b>{n}</b></article>}
function Tile({i,t,s}:{i:string,t:string,s:string}){return <button onClick={()=>alert(t)}><Icon>{i}</Icon><b>{t}</b><span>{s}</span></button>}
function Panel({title,children}:{title:string,children:React.ReactNode}){return <section className="panel"><h3>{title}</h3>{children}</section>}
function Progress({t,p}:{t:string,p:string}){return <div className="progress"><b>{t}</b><span>{p}%</span><i><u style={{width:p+'%'}}/></i></div>}
function Row({n,t}:{n:string,t:string}){return <div className="row"><b>{t}</b><span>{n}</span></div>}
function Subject({i,t,p}:{i:string,t:string,p:string}){return <button onClick={()=>alert(t)}><Icon>{i}</Icon><b>{t}</b><strong>{p}%</strong><i><u style={{width:p+'%'}}/></i></button>}
function Schedule({c,i,t,time}:{c:string,i:string,t:string,time:string}){return <div className={`schedule ${c}`}><Icon>{i}</Icon><b>{t}</b><span>{time}</span></div>}
function Task({i,t,s}:{i:string,t:string,s:string}){const [done,setDone]=React.useState(false);return <button className={`task ${done?'done':''}`} onClick={()=>setDone(!done)}><span className="check">{done?'✓':''}</span><Icon>{i}</Icon><b>{t}</b><small>{s}</small></button>}
function Nav({teacher=false,goStudent,goTeacher}:{teacher?:boolean;goStudent?:()=>void;goTeacher?:()=>void}){return <nav className="bottom"><button>🏠<b>الرئيسية</b></button>{teacher?<button onClick={goStudent}>👥<b>الطلاب</b></button>:<button>📖<b>المواد</b></button>}<button className="shika" onClick={teacher?goStudent:goTeacher}>👽<b>شكابمبو</b></button><button>📖<b>الكتب</b></button><button>•••<b>المزيد</b></button></nav>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
